# Generated by Django 4.0.2 on 2022-04-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trade_setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('coin', models.CharField(max_length=10)),
                ('entry', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stop_loss', models.DecimalField(decimal_places=2, max_digits=5)),
                ('take_profit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exit_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
